server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://localhost:8081
          predicates:
            - Path=/payments/**, 
        - id: cafe
          uri: http://localhost:8082
          predicates:
            - Path=/cafeOrders/**, 
        - id: shop
          uri: http://localhost:8083
          predicates:
            - Path=/menus/**, 
        - id: order
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**, /orderLists/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: cafe
          uri: http://cafe:8080
          predicates:
            - Path=/cafeOrders/**, 
        - id: shop
          uri: http://shop:8080
          predicates:
            - Path=/menus/**, 
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, /orderLists/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
